print("Summer is all about the beach! During the daytime, you can [verb]")
verb = input("Enter a verb: ")
print("in the lake or sea and collect seashells and [noun].")
noun = input("Enter a noun: ")
print("a meal of [adjective] hot dogs")
adj = input("Enter an adjective: ")
print("and [adjective] ice cream.")
adj2 = input("Enter a adjective: ")
print("They're [adverb] yummy.")
adv = input("Enter a adverb: ")
print("You might see [noun]")
noun2 = input("Enter a noun: ")
print("and [noun].")
noun3 = input("Enter a noun: ")
print("A day at the beach is [adverb]")
adv2= input("Enter a adverb: ")

print("Summer is all about the beach! During the daytime, you can " + verb)
print("in the lake or sea and collect seashells and " + noun + ". Then feast on")
print("a meal of " + adj + " hot dogs and " + adj2 + " ice cream.")
print("They're " + adv + " yummy. After that, rest on a boat as you catch")
print(" some of the sun's bright rays. As the sunlight slowly slips away,")
print("you can rest and view the nighttime sky. You might see " + noun2 + " and " + noun3 + ".")
print("All that's left to do is whisper, \"good night.\" A day at the beach is " + adv2)
print("a treat unless it rains, of course!")